# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbx < Formula
  desc ""
  homepage "https://github.com/etng/homebrew-taps"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etng/bbx/releases/download/v0.0.3/bbx_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "462fd5a77dedd26be79616cd447bb87ff5ff788680d63f0306321bf8c066640b"

      def install
        bin.install "bbx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etng/bbx/releases/download/v0.0.3/bbx_0.0.3_Darwin_arm64.tar.gz"
      sha256 "6d3670105418adb677cc3206e59ce409569328e7155b1324254218b5d8da92b0"

      def install
        bin.install "bbx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/etng/bbx/releases/download/v0.0.3/bbx_0.0.3_Linux_x86_64.tar.gz"
      sha256 "dbf90ac2fa025bce6904ed827ce375dc424c007e2901ab81b401da3063a36435"

      def install
        bin.install "bbx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etng/bbx/releases/download/v0.0.3/bbx_0.0.3_Linux_arm64.tar.gz"
      sha256 "246c1604d3d04f7fec4a40b6a9ffc7e477e089a7de2334d2654c8851f04181d1"

      def install
        bin.install "bbx"
      end
    end
  end
end
