# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbx < Formula
  desc ""
  homepage "https://github.com/etng/homebrew-taps"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etng/bbx/releases/download/v0.0.5/bbx_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "c3f54c6fba940a762c142f78203d044a955d0adbad3304e3c732f4983fb81c9b"

      def install
        bin.install "bbx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etng/bbx/releases/download/v0.0.5/bbx_0.0.5_Darwin_arm64.tar.gz"
      sha256 "2931099aad2f6861f40cf6e361987b3a08a16a3178022be25b29aa8a4d87db78"

      def install
        bin.install "bbx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/etng/bbx/releases/download/v0.0.5/bbx_0.0.5_Linux_x86_64.tar.gz"
      sha256 "75770b1e47a96bc26d84e4745c25fc6d9b0136ca68ef7991e37bb23af9775d9f"

      def install
        bin.install "bbx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etng/bbx/releases/download/v0.0.5/bbx_0.0.5_Linux_arm64.tar.gz"
      sha256 "d184dac1fb5cebe5c224d12a42b0e8894b4f8ff49c77941d76f63c976d1c9cb6"

      def install
        bin.install "bbx"
      end
    end
  end
end
