# This file was generated by the AutoZ release workflow. DO NOT EDIT.
#
# 源模板: https://github.com/etng/autoz  →  .github/templates/autoz.rb.tmpl
# 每次在 etng/autoz 打 v* tag 时，发布流水线会重新生成本文件并推送到本仓库。
cask "autoz" do
  version "1.2.0"
  sha256 "b0ac0ccc90f2a9448ae81768ef3de93160885037d90b85e7c826e27da4ee53fa"

  url "https://github.com/etng/autoz/releases/download/v#{version}/AutoZ-#{version}.tar.gz"
  name "AutoZ"
  desc "Menu bar clock pinned to UTC+8 that syncs the system timezone to your exit IP"
  homepage "https://github.com/etng/autoz"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :ventura

  app "AutoZ.app"

  postflight do
    # 应用未做 Apple 公证（ad-hoc 签名）。下载后会被打上隔离标记，
    # 不去掉的话首次打开会被 Gatekeeper 拦下报「已损坏」。
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/AutoZ.app"]
  end

  caveats <<~EOS
    AutoZ 未做 Apple 公证，安装时已自动清除隔离标记。
    若打开时仍提示「已损坏」，请手动执行：
      xattr -dr com.apple.quarantine /Applications/AutoZ.app

    想让改时区时不再弹管理员密码框，首次使用请在
    「高级配置…」→ 改时区方式 里安装一次免授权助手。

    卸载前建议先卸载免授权助手（「高级配置…」→ 卸载免授权助手）。
  EOS

  zap trash: [
    "~/Library/Application Support/AutoZ",
    "~/Library/Logs/AutoZ.log",
    "~/Library/Preferences/cn.y10n.autoz.plist",
    "~/Library/Saved Application State/cn.y10n.autoz.savedState",
  ]
end
